import type { Metadata } from "next";
import { Gruppo } from "next/font/google";
import "./styles/globals.css";

const gruppo = Gruppo({
  subsets: ['latin', 'latin-ext'],
  variable: '--font-gruppo',
  weight: '400',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "KiQ Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gruppo.variable} bg-zinc-950 text-indigo-50 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
